# Site settings
title: CokAPP
email: office@cokapp.com
description: "focus on web"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: cokapp.com
  location: ChangSha
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cokapp
  - title: weibo
    url: http://weibo.com/cokapp
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/cokapp
  - title: bitbucket 
    url: http://bitbucket.org/cokapp
  - title: github
    url: http://github.com/cokapp

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
  
# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
